CREATE TABLE PERSONAL (
    PERSON_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    GENDER CHAR(1),
    DATE_OF_BIRTH DATE,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(100),
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(100),
    IS_DELETE CHAR(1) DEFAULT 'N'
)


CREATE TABLE ADDRESS (
    ADDRESS_ID SERIAL PRIMARY KEY,
    PERSON_ID INT NOT NULL,
    ADDRESS_NAME VARCHAR(255) NOT NULL,
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    ZIP_CODE VARCHAR(20),
    COUNTRY VARCHAR(100),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(100),
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR(100),
    IS_DELETE CHAR(1) DEFAULT 'N',
    FOREIGN KEY (PERSON_ID) REFERENCES PERSONAL(PERSON_ID) ON DELETE CASCADE
);
